#include "Atom/Logging/LogTarget.h"
#include "Atom/Logging/LogTargets/ConsoleLogTarget.h"
#include "Atom/Logging/Logger.h"
#include "Atom/Logging/LoggerRegistry.h"
#include "Atom/Logging/NullLogger.h"
